apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: ska
  source:
    chart: metrics-server
    helm:
      version: v3
      values: |
{{ .Files.Get "metrics-server-values.yaml" | indent 8 }}
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.8.2
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
    - CreateNamespace=true
